### ISSUE TITLE
Problem with theta_snippet_score and logging.

### ISSUE THREAD

**Issue by doykov** [bigartm/bigartm#111]
Hello!

I try to use BigARTM on mac os.
I have a problem with theta_snippet_score: it doesn't work.

In example02_parse_collection.py it writes 'Snippet of theta matrix:' in the end and nothing more.

Also sometimes a have an error on my screen with logging:
'Could not create logging file: No such process
COULD NOT CREATE A LOGGINGFILE 20150205-205823.2054!'
But this file is created.

**Comment by sashafrey** [comment]
Thank you for the report!
I'm able to reproduce this on my machine. This is a recent regression (we overlooked that theta_snippet_score haven't been covered with unit tests). I'll work on this ASAP.

**Comment by sashafrey** [comment]
ThetaMatrixSnippet now should work fine in the Master branch. Could you please update and verify if it works for you?

For the logging issue I've opened a separate ticket (https://github.com/bigartm/bigartm/issues/113). I've also seen this issue, and it happens inside glog (Logging library for C++ from Google). I'm sure there are ways to solve this, but I have to debug their code to find out. Let me know if this is critical, otherwise I'll just keep this ticket as a reminder and eventually it will be fixed (but not next month).

**Comment by doykov** [comment]
Yes, I've updated and now ThetaMatrixSnippet works well.
Thank you!

**Comment by bigartm** [comment]
Verified by submitter. Closing the ticket.
