### ISSUE TITLE
Analysis of short and noisy text documents

### ISSUE THREAD

**Issue by usptact** [bigartm/bigartm#428]
Hi,

I am relatively new to the field of topic modeling, especially the technical part of the methods. I am looking into topic modeling of short text documents (typically 3-7 words per document). From literature I've read that the standard LDA and PLSA algorithms don't work because of the scarcity of words. Additional issue is the noise in such text documents which requires an algorithm to be also robust to noisy features.

The short text documents can be very often modeled with one or at most two topics. This means that a document representation using topics should be rather sparse.

My question is: Will the framework work also on short text documents? If yes, what regularizers are known to be working is such setting?

I read all four papers about ARTM and did not notice any comment about short text documents.

Thanks for sharing out the software!

**Comment by AnyaP** [comment]
Hi, 

Indeed, standard topic models are known to perform poorly for short texts, but a number of improvements can be done.

First, I would recommend to use a term-term matrix instead of a document-term matrix as the data for learning topics. In the case of 3-7 words per document, it would be reasonable to treat the elements n_{ij} in this matrix as "the number of documents that contain both term i and j". A similar approach but with other optimization techniques is used here for tweets analysis:  http://shortext.org/paper/TNMF-SDM13.pdf.

Once a topic model is learned (Phi matrix is found), you can transform your initial documents based on it (find Theta matrix for them). As you have said, Theta vectors should be highly sparse. To achieve this, add the sparsing regularizer to the model with a relatively large coefficient.

Please, feel free to ask further questions!

Best,
Anna

**Comment by usptact** [comment]
Hi Anna,

Thank you for very valuable suggestion. I tried at 4-5 different techniques with accent on short text analysis. Currently the top performers are Bi-Term LDA and NNMF.

I have a question about background and trash topic functionality in BigARTM. How these topics are discovered? Are they special? Can I read about them more? I have some documents which are difficult to model with topics (typically junk utterances or very short documents with very varying words).

Thanks

**Comment by sashafrey** [comment]
I can try to answer with BigARTM CLI example:
```
* Fit more advanced regularize model, with 10 sparse objective topics, and 2 smooth background topics:
  bigartm -d docword.kos.txt -v vocab.kos.txt --dictionary-max-df 50% --dictionary-min-df 2
          --passes 10 --batch-size 50 --topics obj:10;background:2 --write-model-readable model.txt
          --regularizer "0.05 SparsePhi #obj"
          --regularizer "0.05 SparseTheta #obj"
          --regularizer "0.25 SmoothPhi #background"
          --regularizer "0.25 SmoothTheta #background"
```
Here you define a model that will have `12` topics in total - 10 objective, and 2 trash. Just because you put obj:10 before background:2 objective topics will be numbered 0..9 in your model, and trash topics will get indices 10 and 11. At this moment `objective` and `background` are just labels. To treat them differently we enable regularizers, and say that objective topics should be SPARSE, while trash topics should be SMOOTH (meaning "not sparse", e.g. have no zeros).

@AnyaP Do you have something to add for this description?

**Comment by usptact** [comment]
Hi @sashafrey,

Thanks for the example! It looks like the names of the labels are arbitrary, it is only the regularizer that treats each group differently. Basically we want interpretable (sparse) model for the topics of interest and put everything else unconstrained, just smooth as in the PLSA with no regularization. Here I have a question about regularization signs. I remember at one point the documentation mentioned opposite signs. Is this relevant for this obj vs background modeling here?

**Comment by sashafrey** [comment]
Yes, that's correct - mathematically the `SmoothPhi` and `SparsePhi` differ just by the sign of the regularization value that is added (or substracted) from the `n_wt` counters. In command-line interface we decided to split these two concepts into separate regularizers, and both of them expect positive regularization constants. In C++ and Python APIs these two regularizers show up as a single regularizer called `SmoothSparsePhi`, which can accept both negative and positive regularization values. Negative value `tau < 0` would correspond to `SparsePhi:tau'` with `tau' = |tau| > 0`, and positive `tau` would correspond to `SmoothPhi:tau`.

Same applies to `SmoothTheta` and `SparseTheta`. Both expect positive constants, exist only in BigARTM command-line interface, and correspond to internal regularizer `SmoothSparseTheta` which accepts both negative values (=> sparsity) and postiive values (=>smooth).
