### ISSUE TITLE
Build failure: linking error under Mac OS X

### ISSUE THREAD

**Issue by usptact** [bigartm/bigartm#429]
[ 80%] Linking CXX shared library libartm.dylib
Undefined symbols for architecture x86_64:
  "boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&)", referenced from:
      artm::core::BatchHelpers::ListAllBatches(boost::filesystem::path const&) in libartm-static.a(helpers.cc.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/artm/libartm.dylib] Error 1
make[1]: *** [src/artm/CMakeFiles/artm.dir/all] Error 2
make: *** [all] Error 2

Mac OS X 10.11.3
I have Boost 1.59.0 installed using the Mac Ports.

**Comment by sashafrey** [comment]
I'm not able to verify myself since I have no MAC OS at hand, but I would suggest to modify [Line 49 in CMakeLists.txt](https://github.com/bigartm/bigartm/blob/master/CMakeLists.txt#L49)  to include `-stdlib=libstdc++`:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pthread -fPIC  -stdlib=libstdc++") 
```
To be sure I would completely remove `build` folder and re-generate it from scratch via `CMake ..`.

Some relevant posts on stackoverflow:
* http://stackoverflow.com/questions/19637164/c-linking-error-after-upgrading-to-mac-os-x-10-9-xcode-5-0-1
* http://stackoverflow.com/questions/12770115/linking-libraries-opencv-2-4-2-on-xcode-4-5-1

**Comment by usptact** [comment]
Hi Sashafrey,

The actual flag with clang++ is -stdlib=libc++. Thanks a lot for the pointer, the software compiles and runs successfully now!

**Comment by JeanPaulShapo** [comment]
@usptact Sorry for inconvenience, but could you write how you change CMakeLists.txt in order to build successfully?

**Comment by usptact** [comment]
Hi JeanPaulShapo,

I managed to compile the binary using Apple's Clang tool, not GCC 4.9 which I was using all the time. Then I modified the line 49 as @sashafrey mentioned but by putting an additional parameter -stdlib=libc++. Currently I don't have access to the machine but that should be easy to do. I did no other changes.
