### ISSUE TITLE
W0130 21:35:24.425745 2041622528 master_component.cc:590] Model nwt does not exist

### ISSUE THREAD

**Issue by usptact** [bigartm/bigartm#431]
Occurs when loading an existing model for the second iteration. I am following the two step topic learning from the bigartm-book but with my own data. This warning appears at the second step.

**Comment by sashafrey** [comment]
Could you give a link to the bigartm-book notebook that you use to reproduce this? I'm not exactly sure which one you refer to...

I'm just guessing now, but it is likely that you run `fit_online` after `artm.load(...)`. In this case there will be no `nwt` matrix because `artm.Save()` only saves the `pwt` matrix (e.g. the *normalized* Phi matrix in terms of ARTM theory). This information is enough to continue infer topic distribution for new items, or to continue model tuning with `fit_offline`. In order to continue model tuning with `fit_online` we should also save the `nwt` matrix (e.g. *non-normalized` counters), but so far this scenario hasn't been not discussed.

Could you tell us a little bit more about your scenario? What is the end goal of your script?

**Comment by usptact** [comment]
Hi,

I am using the binary for topic analysis and prediction only.No python. I should take some time to get back to the example and post more details setting of my experiment.

From the top of my head, this is the example where a 'vanilla' model first is fit with most parameters at default values. Then in the second step the regularizers are enabled and thus the final model (and predictions?) are written out.

**Comment by sashafrey** [comment]
I see. Could you copy the command-line commands that run? Particularly, I'm interested if you are using `--update-every` switch in the second command, but it would be great to see the whole command, too..

**Comment by usptact** [comment]
Hi @sashafrey,

I will try to find time and get back to the experiment I ran last time. I am pretty certain that I did not use the --update-every switch at all.

**Comment by sashafrey** [comment]
Wow, if this happens without --update-every then this is indeed very interesting. Please let me know what commands lead to this, if you could recover them...

**Comment by usptact** [comment]
This gives me more motivation to get back and re-run it! I will try to reproduce it!

**Comment by usptact** [comment]
Hmm, I tried to reproduce the commonds I ran but did not get this error again. Perhaps I mixed some incompatible parameters while messing with console. I regret that I did not document the issue immediately when it appeared.
