### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Zmeu213** [bigartm/bigartm#660]
Errors in make process 
cmake version 3.6.2;
Ubuntu 13.10

```
[ 92%] Building CXX object src/artm_tests/CMakeFiles/artm_tests.dir/thread_safe_holder_test.cc.o
/home/oppex/bigartm-test/bigartm/src/artm_tests/thread_safe_holder_test.cc: In member function 'virtual void Async_Boost_Test::TestBody()':
/home/oppex/bigartm-test/bigartm/src/artm_tests/thread_safe_holder_test.cc:40:96: error: conversion from 'boost::unique_future<void>' to non-scalar type 'boost::unique_future<int>' requested
   boost::unique_future<int> fut = boost::async(boost::launch::async, [input](){ return input; });
                                                                                                ^
make[2]: *** [src/artm_tests/CMakeFiles/artm_tests.dir/thread_safe_holder_test.cc.o] Error 1
make[1]: *** [src/artm_tests/CMakeFiles/artm_tests.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ofrei** [comment]
@Zmeu213 I'm not able to reproduce this so far. Which compiler do you use? The recommended compiler for BigARTM is GCC 4.8.1 or higher (which, according to [GCC website](https://gcc.gnu.org/projects/cxx-status.html#cxx11), is "the first feature-complete implementation of the 2011 C++ standard"). However, BigARTM's continuous integration builds runs on GCC 4.6.3, using Ubuntu 12.04.5.

You may also choose to ignore this error because it happens while building unit-tests. There is a build option to not build tests: 
``cmake .. -DBUILD_BIGARTM_CLI=false``

**Comment by Zmeu213** [comment]
@ofrei, my gcc version 4.8.1 as recomended.

**Comment by ofrei** [comment]
Ok, good it works without tests (though I'll do need to update the documentation to mention setuptools). But for the very first build error -- I'll just remove the unit test that caused build error. The test was just a convenient way play with boost::async, but this is no longer relevant as in BigARTM we decided to use std::async (not boost:async).  

Btw, the build error was from the following code, which to me looks like a perfectly valid C++ code.  If anyone knows why GCC 4.8.1 isn't happy please let me know...
```
int input = 123;
boost::unique_future<int> fut = boost::async(boost::launch::async, [input](){ return input; });
```
