### ISSUE TITLE
is it open source project , meaning if all source files are available?

### ISSUE THREAD

**Issue by Sandy4321** [bigartm/bigartm#842]
I see cc files in project, does it means all code is open sourced
or there are some exe or dll files which hide some code
thanks

**Comment by ofrei** [comment]
Entire source code is available in this repository. The only external dependencies we take as binaries is visual studio redistributable (run-time libraries), because this is unavoidable as long as we build with Visual Studio. Clearly vs redistributables do not hide any logic related to topic modeling.   All other external dependencies have their source code available (for C++ --- boost, google protobuf, glog and log, for python - numpy, pandas).
