### ISSUE TITLE
NetPLSA Implementation

### ISSUE THREAD

**Issue by shayantabrizi** [bigartm/bigartm#863]
There is some ambiguity in the NetPLSA implementation. If it is according to Mei et al., "Topic Modeling with Network Regularization", it should regularize according to theta, while NetPLSA implementation regularizes according to phi. Also, its formula is different from the covariance regularization formula in the ARTM paper, so it seems that it is different from that too. So, what is the implemented NetPLSA exactly?

**Comment by shayantabrizi** [comment]
It seems that in "Fast and Modular Regularized Topic Modelling," this is discussed. However, doesn't treating links as a modality make the possible problem cause by the exchangeability assumptions worse?

p.s. In "Relational Topic Models for Document Networks" it mentions: Closest to the RTM is recent work by Nallapati et al. (2008) and Mei et al. (2008), which attempts to address these issues by extending the mixed-membership stochastic block model (Airoldi et al. 2008) to include word attributes. **Because of their underlying exchangeability assumptions, these models allow for the links to be explained by some topics and the words to be explained by others.** This hinders their predictions when using information about words to predict link structure and vice versa. In contrast, the RTM enforces the constraint that topics be used to explain both words and links. We

**Comment by ofrei** [comment]
@AnyaP Do you know how to answer this?

**Comment by ofrei** [comment]
@shayantabrizi 
>It seems that in "Fast and Modular Regularized Topic Modelling," this is discussed.
Yes, you are right - that paper explains how to re-write NetPLSA so that it acts on phi instead of theta. Operations on phi are easier to implement in BigARTM because phi is stored in memory, while documents are streamed from disk (so we don't need to store entire theta matrix in memory).

To your question on exchangeability, unfortunately I'm not able to answer. I suggest to send e-mail to authors of "Fast and Modular Regularized Topic Modelling". This is scientific discussion which doesn't really fit to github issue format.

**Comment by shayantabrizi** [comment]
Ok. Thanks.
